### ISSUE TITLE
Shiny code is up

### ISSUE THREAD

**Issue by jpeters7** [PalEON-Project/Shiny#1]
@SimonGoring, @paciorek finally got our Shiny code up on GitHub!

The main issue I need help with is visualizing the maps.  I can create the maps using the maps.R file and we have the ui.R file that controls how the webpage looks. But we can't get the server.R file to work.
You'll see some code at the top regarding a Canada shapefile.  Alex Dye sent code he had been working on for a Shiny App course, so we played around with that. Then we also have code at the bottom where we tried to plug in the code from maps.R. But we were not able to get the US albers shapefile to visualize and therefore was unable to visualize the maps. 

I haven't had time to look at the leaflet package Simon mentioned on our phone call, but will do so soon.

**Comment by paciorek** [comment]
I'm off this coming week so won't have a chance to look at it in detail for
a bit, but will try to do so soon after I get back.

To clarify: if you ignore the plotting of the state boundaries, can you get
Shiny to work just in terms of plotting the raster images of the
composition estimates on a simple x-y grid - the Albers x-y we are using?
I.e. if you use my ggplot2 code w/o the add_map_albers part, does it work?

I'm a bit confused as to what you are trying to do - why are you trying to
first plot the shapeFile and then use make_veg_map?  Does it not work to
simply read in and create usFortified and pass that to make_veg_map, which
calls add_map_albers to overlay the state boundaries?  Without delving
deeply, it would appear to me that initial plotting of the shapeFile in
server.R would use base R graphics and not ggplot2 and then make_veg_map
would come along and wipe out the initial plot and create a ggplot2 plot.

**Comment by SimonGoring** [comment]
I think this can be closed, we don;t have an active issue here now.  I'm going to tag the repo as it stands as version 0.1, since it works as a bare-bones structure.  We can make it nicer and stuff, but for now it 'just works'.

It would be good to make new issues now for the things we want to make nicer. @paciorek @jpeters7 @andydawson and any others, can you clone & run the repo and make bug reports and enhancement notes?
