### ISSUE TITLE
other projections for leaflet version

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/Shiny#15]
If we use the underlying map, are we stuck with the terrible projection we currently have?

**Comment by SimonGoring** [comment]
Yes.  But it lets up pan and zoom more easily. I'll check with Rob Roth
though and see if there are any other options.

**Comment by SimonGoring** [comment]
I think that this is beyond my capabilities at present.  I'm going to leave this issue open, but unless we have a custom tileset it's going to be really difficult to get the functionality we currently have.

**Comment by SimonGoring** [comment]
I'm going to close this issue.  I don't think this is a key need at present.
