### ISSUE TITLE
panning/zooming in second panel not mirrored in first panel

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/Shiny#16]
changes in first panel are mirrored in second but not the reverse. Not sure if this is a new problem or not.

**Comment by SimonGoring** [comment]
It's a solution to a bug, not a bug itself.  With the two panels chained to each other we were getting a situation where the two panels would respond to one another in a loop.  It also led to a second issue where the initial zoom level seemed to default to the global view.  I'm not sure why.  The change occurred in commit 29146f9a835814270c836c6391a91b48b235a760.

I think we should leave it as is.
