### ISSUE TITLE
Folder names should be standardized for unix systems.

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/Shiny#3]
My guess is that we should remove capitalization and spaces in the folder and file names if we're going to be running this on a server.

@paciorek does that make sense?  You use linux/unix more than me. . .

**Comment by SimonGoring** [comment]
This should be fine now, although there are a bunch of extraneous directories, I'm not sure what they're for.

**Comment by paciorek** [comment]
taking out spaces is a very good idea.

UNIX is case-sensitive, so it may be simplest to use all lower case for
directories if you don't want to be confused in going back and forth to
windows.
