### ISSUE TITLE
Better maps

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/Shiny#6]
The maps need the following things:
- [x] overlaid political boundaries
- [x] bigger (?) displays
- [x] prettier gradients
- [x] Mean and SD titles for each Map 

It's up for debate, but that's my starting point.

**Comment by paciorek** [comment]
Some of this is addressed in the current commit - the code there shows how to do these things but hasn't fully implemented everything each of the maps.
- [ x ] overlaid political boundaries
- [ x ] bigger (?) displays
- [ x ] prettier gradients
- [ x ] Mean and SD titles for each Map 

As far as prettier gradients, I implemented the discrete scale I use in the PDF output for the stat composition paper and pdfs on the Wiki.

**Comment by SimonGoring** [comment]
I think commits a8a7967d0393345e74169a72aa3be4122a6fd493 and 32e0f3fbe7e96ff0210fcca79eb4af47a1457a59 deal with these issues well enough for v0.2.
